CREATE USER springuser;

ALTER USER springuser WITH PASSWORD '---';

CREATE DATABASE investing;

CREATE DATABASE "investing"
    WITH OWNER "postgres"
    ENCODING 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TEMPLATE template0;

GRANT ALL PRIVILEGES ON DATABASE investing TO springuser;

INSERT INTO activo (ticker,tipo_activo,descripcion)
VALUES
('AAPL','CEDEAR','Apple Inc.'),
('ABEV','CEDEAR','Ambev SA ADR'),
('ABT','CEDEAR','Abbott Laboratories'),
('ADBE','CEDEAR','Adobe Inc'),
('AGRO','CEDEAR','Adecoagro SA'),
('AIG','CEDEAR','American International Group Inc'),
('AMD','CEDEAR','Advanced Micro Devices, Inc.'),
('AMGN','CEDEAR','Amgen, Inc.'),
('AMX','CEDEAR','America Movil SAB de CV ADR'),
('AMZN','CEDEAR','Amazon.com, Inc.'),
('ARCO','CEDEAR','Arcos Dorados Holdings Inc'),
('AUY','CEDEAR','Yamana Gold Inc'),
('AXP','CEDEAR','American Express Company'),
('BA','CEDEAR','Boeing Co'),
('BABA','CEDEAR','Alibaba Group Holding Ltd ADR'),
('BBD','CEDEAR','Banco Bradesco SA'),
('BCS','CEDEAR','Barclays PLC'),
('BHP','CEDEAR','BHP Group Ltd'),
('BIDU','CEDEAR','Baidu Inc'),
('BIIB','CEDEAR','Biogen Inc'),
('BMY','CEDEAR','Bristol-Myers Squibb Co'),
('BP','CEDEAR','BP plc'),
('BRFS','CEDEAR','CEDEAR,BRF S.A. ADR'),
('BSBR','CEDEAR','Banco Santander Brasil SA ADR'),
('C','CEDEAR','Citigroup Inc'),
('CAT','CEDEAR','Caterpillar Inc.'),
('CHL','CEDEAR','China Mobile Ltd.'),
('CL','CEDEAR','Colgate-Palmolive Company'),
('COST','CEDEAR','Costco Wholesale Corporation'),
('CRM','CEDEAR','salesforce.com, inc.'),
('CS','CEDEAR','Credit Suisse Group AG'),
('CSCO','CEDEAR','Cisco Systems, Inc.'),
('CVX','CEDEAR','Chevron Corporation'),
('CX','CEDEAR','Cemex SAB de CV ADR'),
('DD','CEDEAR','DuPont de Nemours Inc'),
('DE','CEDEAR','Deere & Company'),
('DESP','CEDEAR','Despegar.com Corp'),
('DIS','CEDEAR','Walt Disney Co'),
('EBAY','CEDEAR','eBay Inc'),
('ERJ','CEDEAR','Embraer SA'),
('FB','CEDEAR','Facebook, Inc. Common Stock'),
('FCX','CEDEAR','Freeport-McMoRan Inc'),
('FDX','CEDEAR','FedEx Corporation'),
('FMX','CEDEAR','Fomento Economico Mexicano SAB ADR'),
('GAZP','CEDEAR','PJSC GAZPROM '),
('GE','CEDEAR','General Electric Company'),
('GGB','CEDEAR','CEDEAR,Gerdau SA ADR'),
('GILD','CEDEAR','Gilead Sciences, Inc.'),
('GLOB','CEDEAR','Globant SA'),
('GOLD','CEDEAR','Barrick Gold Corp'),
('GOOGL','CEDEAR','Alphabet Inc Class A'),
('GRMN','CEDEAR','Garmin Ltd.'),
('GS','CEDEAR','Goldman Sachs Group Inc'),
('GSK','CEDEAR','GlaxoSmithKline plc'),
('HD','CEDEAR','Home Depot Inc'),
('HMC','CEDEAR','Honda Motor Co Ltd'),
('HMY','CEDEAR','Harmony Gold Mining Co.'),
('HNP','CEDEAR','Huaneng Power International Inc ADR'),
('HPQ','CEDEAR','HP Inc'),
('HSBC','CEDEAR','HSBC Holdings plc'),
('HWM','CEDEAR','Howmet Aerospace Inc'),
('IBM','CEDEAR','IBM Common Stock'),
('INFY','CEDEAR','Infosys Ltd ADR'),
('INTC','CEDEAR','Intel Corporation'),
('ITUB','CEDEAR','Itau Unibanco Holding SA ADR'),
('JD','CEDEAR','JD.Com Inc'),
('JNJ','CEDEAR','Johnson & Johnson'),
('JPM','CEDEAR','JPMorgan Chase & Co.'),
('KMB','CEDEAR','Kimberly Clark Corp'),
('KO','CEDEAR','Coca-Cola Co'),
('LMT','CEDEAR','Lockheed Martin Corporation'),
('LVS','CEDEAR','Las Vegas Sands Corp.'),
('LYG','CEDEAR','Lloyds Banking Group PLC'),
('MCD','CEDEAR','Mcdonalds Corp'),
('MDT','CEDEAR','Medtronic PLC'),
('MELI','CEDEAR','Mercadolibre Inc'),
('MMM','CEDEAR','3M Co'),
('MO','CEDEAR','Altria Group Inc'),
('MRK','CEDEAR','Merck & Co., Inc.'),
('MSFT','CEDEAR','Microsoft Corporation'),
('MSI','CEDEAR','Motorola Solutions Inc'),
('NEM','CEDEAR','Newmont Corporation'),
('NFLX','CEDEAR','Netflix Inc'),
('NGG','CEDEAR','National Grid plc'),
('NKE','CEDEAR','Nike Inc'),
('NOK','CEDEAR','Nokia Oyj'),
('NVDA','CEDEAR','NVIDIA Corporation'),
('NVS','CEDEAR','Novartis AG'),
('ORCL','CEDEAR','Oracle Corporation'),
('PBR','CEDEAR','PETROLEO BRASIL ADR'),
('PEP','CEDEAR','PepsiCo, Inc.'),
('PFE','CEDEAR','Pfizer Inc.'),
('PG','CEDEAR','Procter & Gamble Co'),
('PTR','CEDEAR','PetroChina Company Limited ADR'),
('PYPL','CEDEAR','Paypal Holdings Inc'),
('QCOM','CEDEAR','QUALCOMM, Inc.'),
('RIO','CEDEAR','Rio Tinto plc ADR'),
('RTX','CEDEAR','Raytheon Technologies Corp'),
('SAN','CEDEAR','CEDEAR,Banco Santander SA'),
('SAP','CEDEAR','SAP SE'),
('SBS','CEDEAR','Companhia de Saneamento Bsc DEDSP'),
('SBUX','CEDEAR','Starbucks Corporation'),
('SID','CEDEAR','CEDEARCEDEAR,Companhia Siderurgica Nacional'),
('SLB','CEDEAR','Schlumberger NV'),
('SNAP','CEDEAR','Snap Inc'),
('SNE','CEDEAR','Sony Corp'),
('SNP','CEDEAR','China Petroleum & Chemical Corp ADR'),
('T','CEDEAR','AT&T Inc.'),
('TGT','CEDEAR','Target Corporation'),
('TM','CEDEAR','Toyota Motor Corp'),
('TOT','CEDEAR','Total SA'),
('TRIP','CEDEAR','Tripadvisor Inc Common Stock'),
('TSLA','CEDEAR','Tesla Inc'),
('TSM','CEDEAR','CEDEAR,Taiwan Semiconductor Mfg. Co. Ltd.'),
('TSU','CEDEAR','TIM Participacoes SA'),
('TWTR','CEDEAR','Twitter Inc'),
('TXN','CEDEAR','Texas Instruments Incorporated'),
('UGP','CEDEAR','Ultrapar Participacoes SA'),
('UN','CEDEAR','Unilever NV'),
('V','CEDEAR','Visa Inc'),
('VALE','CEDEAR','Vale SA'),
('VIST','CEDEAR','VISTA OIL & GAS ADR'),
('VIV','CEDEAR','Telefonica Brasil SA ADR'),
('VOD','CEDEAR','Vodafone Group Plc'),
('VRSN','CEDEAR','Verisign, Inc.'),
('VZ','CEDEAR','Verizon Communications Inc.'),
('WFC','CEDEAR','Wells Fargo & Co'),
('WMT','CEDEAR','Walmart Inc'),
('X','CEDEAR','United States Steel Corporation'),
('XOM','CEDEAR','Exxon Mobil Corporation'),
('YELP','CEDEAR','Yelp Inc');
